---
development:
  database: tech_radar_development
  dialect: postgres
  user: lukas
  password: ~
  host: 127.0.0.1
  pool: 5

test:
  database: tech_radar_test
  dialect: postgres
  user: lukas
  password: ~
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/tech_radar_production?sslmode=disable"}}
